### ISSUE TITLE
Batseba amaniel - cs3
Assignment v1,v2,v3 ciphering 

### ISSUE THREAD

**Issue by Amanbatseba** [samiromer2/samiromer2#2]
https://github.com/Amanbatseba/caesar-cypher

**Comment by samiromer2** [comment]
still missing the v2 and v3/

**Comment by Amanbatseba** [comment]
Hello, isn't monoalphabetic and polyalphabetic ciphering  as v2 and v3?

**Comment by samiromer2** [comment]
no.

    On Thursday, August 4, 2022 at 04:36:37 AM PDT, Amanbatseba ***@***.***> wrote:  
 
 

Hello, isn't monoalphabetic and polyalphabetic ciphering as v2 and v3?
